services:
  db:
    image: postgres:16
    container_name: fs_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fs_user
      POSTGRES_PASSWORD: fs_password
      POSTGRES_DB: fs_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
